<script setup>
import { Head, Link, router, useForm, usePage } from '@inertiajs/vue3';
import { ref } from 'vue';
import SettingsFields from './SettingsFields.vue';
import Pagination from './Pagination.vue';
import { baseUrl } from './engine-ui';

const props = defineProps({ engines: Object, runs: Object, stacks: Object, models: Array, defaults: Object, engineSearch: String });
const activeTab = usePage().url.includes('tab=stacks') ? 'stacks' : usePage().url.includes('tab=discoveries') ? 'discoveries' : 'engines';
const createdStackId = new URLSearchParams(usePage().url.split('?')[1] ?? '').get('created_stack');
const form = useForm({ name: '', test_model_run_id: props.models[0]?.id ?? '', model_run_id: props.models[0]?.id ?? '', settings: { ...props.defaults }, notes: '' });
const defaultSelection = useForm({});
const drawerOpen = ref(false);
const engineSearch = ref(props.engineSearch ?? '');
const search = () => router.get(baseUrl, { engine_search: engineSearch.value || undefined }, { preserveState: true, preserveScroll: true });
const closeDrawer = () => { if (!form.processing) drawerOpen.value = false; };
</script>

<template>
    <Head title="SAT Engines" />
    <div class="mx-auto max-w-7xl space-y-8 px-4 py-8 sm:px-6">
        <header class="flex flex-wrap items-center justify-between gap-4 border-b border-gray-200 pb-4">
            <div><h1 class="text-2xl font-semibold text-gray-900">SAT Engines</h1><p class="mt-1 text-sm text-gray-600">Manage prediction settings and discover candidates against a model’s test season.</p></div>
            <Link :href="`${baseUrl}/discover`" class="rounded bg-gray-900 px-4 py-2 text-sm text-white">Discover settings</Link>
        </header>
        <nav aria-label="SAT engine workspace" class="flex gap-6 border-b border-gray-200">
            <Link :href="baseUrl" :class="activeTab === 'engines' ? 'border-b-2 border-indigo-600 pb-3 text-sm font-medium text-indigo-700' : 'pb-3 text-sm text-gray-600 transition-colors duration-150 hover:text-gray-900 motion-reduce:transition-none'">Engines <span class="ml-1 text-xs tabular-nums">{{ engines.total ?? engines.data.length }}</span></Link>
            <Link :href="`${baseUrl}?tab=discoveries`" :class="activeTab === 'discoveries' ? 'border-b-2 border-indigo-600 pb-3 text-sm font-medium text-indigo-700' : 'pb-3 text-sm text-gray-600 transition-colors duration-150 hover:text-gray-900 motion-reduce:transition-none'">Discoveries <span class="ml-1 text-xs tabular-nums">{{ runs.total ?? runs.data.length }}</span></Link>
            <Link :href="`${baseUrl}?tab=stacks`" :class="activeTab === 'stacks' ? 'border-b-2 border-indigo-600 pb-3 text-sm font-medium text-indigo-700' : 'pb-3 text-sm text-gray-600 transition-colors duration-150 hover:text-gray-900 motion-reduce:transition-none'">Stacks <span class="ml-1 text-xs tabular-nums">{{ stacks.total ?? stacks.data.length }}</span></Link>
        </nav>
        <template v-if="activeTab === 'engines'">
        <section class="space-y-4">
            <div class="flex flex-wrap items-center justify-between gap-3"><form class="flex min-w-64 flex-1 gap-2" @submit.prevent="search"><input v-model="engineSearch" type="search" aria-label="Search engines" placeholder="Search Engines" class="w-full rounded-lg border-gray-300 text-sm shadow-sm focus:border-indigo-500 focus:ring-indigo-500" /><button class="rounded-lg border border-gray-300 px-3 text-sm font-medium text-gray-700 transition-colors duration-150 hover:bg-gray-50 motion-reduce:transition-none">Search</button></form><button type="button" class="inline-flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-600 text-xl font-medium text-white shadow-sm transition-colors duration-150 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 motion-reduce:transition-none" aria-label="Create Engine" @click="drawerOpen = true">+</button></div>
            <div class="overflow-x-auto rounded-xl border border-gray-200 bg-white shadow-sm">
                <table class="w-full text-left text-sm"><thead class="border-b border-gray-200 bg-gray-50 text-xs font-medium uppercase tracking-wide text-gray-500"><tr><th class="p-3">Engine</th><th class="p-3">Stack</th><th class="p-3">Test Model</th><th class="p-3">Production Model</th><th class="p-3">Settings</th><th class="p-3 text-right"><span class="sr-only">Actions</span></th></tr></thead>
                    <tbody><tr v-for="engine in engines.data" :key="engine.id" class="border-b border-gray-100 last:border-0"><td class="p-3"><Link :href="`${baseUrl}/${engine.id}`" class="font-medium text-indigo-700 underline">{{ engine.name }}</Link></td><td class="p-3 text-gray-700"><span v-if="!engine.stack_members?.length">—</span><span v-else class="flex flex-wrap gap-x-2 gap-y-1"><Link v-for="member in engine.stack_members" :key="member.id" :href="`${baseUrl}/stacks/${member.stack.id}`" class="font-medium text-indigo-700 underline">{{ member.stack.name }}<span v-if="member.stack.is_default" class="ml-1 text-gray-500">(default)</span></Link></span></td><td class="p-3 text-gray-700">{{ models.find(model => model.id === engine.test_model_run_id)?.name ?? engine.test_model_run_id }}</td><td class="p-3 text-gray-700">{{ models.find(model => model.id === engine.model_run_id)?.name ?? engine.model_run_id }}</td><td class="p-3 tabular-nums text-gray-700">{{ engine.settings.offense }} / {{ engine.settings.defense }} · {{ engine.settings.confidence_min }}–{{ engine.settings.confidence_max }} · {{ engine.settings.gap }}</td><td class="p-3 text-right"></td></tr></tbody>
                </table>
                <p v-if="!engines.data.length" class="py-10 text-center text-sm text-gray-500">No Engines match this search.</p>
            </div>
            <Pagination :links="engines.links" />
        </section>
        <div v-if="drawerOpen" class="fixed inset-0 z-40" role="presentation"><button type="button" class="absolute inset-0 bg-slate-950/35 transition-opacity duration-200 motion-reduce:transition-none" aria-label="Close create Engine drawer" @click="closeDrawer"></button><aside class="absolute inset-y-0 right-0 flex w-full max-w-xl flex-col bg-white shadow-2xl transition-transform duration-500 ease-out motion-reduce:transition-none" role="dialog" aria-modal="true" aria-labelledby="create-engine-title"><form class="flex h-full flex-col" @submit.prevent="form.post(baseUrl, { onSuccess: closeDrawer })"><header class="flex items-center justify-between border-b border-gray-200 px-6 py-5"><h2 id="create-engine-title" class="text-lg font-semibold text-gray-950">Create Engine</h2><button type="button" class="rounded p-2 text-gray-600 hover:bg-gray-100" aria-label="Close" @click="closeDrawer">×</button></header><div class="flex-1 space-y-5 overflow-y-auto px-6 py-6"><label class="block text-sm font-medium">Name<input v-model="form.name" required maxlength="160" class="mt-1 w-full rounded-lg border-gray-300" /></label><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium">Test Model<select v-model="form.test_model_run_id" required class="mt-1 w-full rounded-lg border-gray-300"><option v-for="model in models" :key="model.id" :value="model.id">{{ model.name }}</option></select></label><label class="text-sm font-medium">Production Model<select v-model="form.model_run_id" required class="mt-1 w-full rounded-lg border-gray-300"><option v-for="model in models" :key="model.id" :value="model.id">{{ model.name }}</option></select></label></div><SettingsFields v-model:settings="form.settings" /><label class="block text-sm font-medium">Notes<textarea v-model="form.notes" maxlength="2000" class="mt-1 w-full rounded-lg border-gray-300" /></label><p v-for="(error, key) in form.errors" :key="key" role="alert" class="text-sm text-red-700">{{ error }}</p></div><footer class="flex justify-end gap-3 border-t border-gray-200 px-6 py-4"><button type="button" :disabled="form.processing" class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium" @click="closeDrawer">Cancel</button><button :disabled="form.processing" class="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{{ form.processing ? 'Creating…' : 'Create Engine' }}</button></footer></form></aside></div>
        </template>
        <section v-else-if="activeTab === 'discoveries'" class="space-y-4">
            <div class="flex items-end justify-between gap-4"><div><h2 class="text-lg font-semibold text-gray-900">Discovery history</h2><p class="mt-1 text-sm text-gray-600">Saved historical evaluations remain available after completion.</p></div><Link :href="`${baseUrl}/discover`" class="rounded border border-gray-300 px-3 py-2 text-sm text-gray-800 transition-colors duration-150 hover:bg-gray-50 motion-reduce:transition-none">New discovery</Link></div>
            <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b border-gray-200 text-xs font-medium uppercase tracking-wide text-gray-500"><th class="p-3">Run</th><th class="p-3">Type</th><th class="p-3">Model</th><th class="p-3">Scope</th><th class="p-3 text-right">Games</th><th class="p-3">Status</th><th class="p-3">Started</th><th class="p-3"><span class="sr-only">Actions</span></th></tr></thead><tbody><tr v-for="run in runs.data" :key="run.id" class="border-b border-gray-100"><td class="p-3 font-medium">{{ run.definition?.name ?? `#${run.id}` }}</td><td class="p-3 capitalize">{{ run.kind }}</td><td class="p-3">{{ run.definition?.model_name ?? run.model_run_id }}</td><td class="p-3">{{ run.definition?.scope?.mode ?? '—' }}</td><td class="p-3 text-right tabular-nums">{{ run.game_count }}</td><td class="p-3"><span class="rounded-full bg-gray-100 px-2 py-1 text-xs font-medium text-gray-700">{{ run.status }}</span></td><td class="p-3 text-gray-600">{{ run.created_at }}</td><td class="p-3 text-right"><Link :href="`${baseUrl}/runs/${run.id}`" class="text-indigo-700 underline">View results</Link></td></tr></tbody></table><p v-if="!runs.data.length" class="py-10 text-center text-sm text-gray-500">No discovery or test runs have been saved yet.</p></div>
            <Pagination :links="runs.links" />
        </section>
        <section v-else class="space-y-5"><div><h2 class="text-lg font-semibold text-gray-950">Saved stacks</h2><p class="mt-1 text-sm text-gray-600">Open a stack to manage its Engines and priority.</p></div><p v-if="createdStackId" role="status" class="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">Stack saved. Its Engines are now available independently.</p><p v-for="(error, key) in defaultSelection.errors" :key="key" role="alert" class="text-sm text-red-700">{{ error }}</p><div class="overflow-x-auto rounded-xl border border-gray-200 bg-white"><table class="w-full text-left text-sm"><thead class="border-b border-gray-200 bg-gray-50 text-xs font-medium uppercase tracking-wide text-gray-500"><tr><th class="px-4 py-3">Stack</th><th class="px-4 py-3">Production model</th><th class="px-4 py-3 text-right">Engines</th><th class="px-4 py-3">Created</th><th class="px-4 py-3"><span class="sr-only">Actions</span></th></tr></thead><tbody><tr v-for="stack in stacks.data" :key="stack.id" class="border-b border-gray-100 last:border-0"><td class="px-4 py-4 font-medium text-gray-950">{{ stack.name }}<span v-if="stack.is_default" class="ml-1 font-normal text-gray-500">(default)</span></td><td class="px-4 py-4 text-gray-600">{{ stack.production_model?.name ?? 'Each Engine' }}</td><td class="px-4 py-4 text-right tabular-nums text-gray-700">{{ stack.members_count }}</td><td class="px-4 py-4 text-gray-600">{{ stack.created_at }}</td><td class="px-4 py-4 text-right"><button v-if="!stack.is_default && stack.members_count" type="button" :disabled="defaultSelection.processing" class="mr-3 text-sm font-medium text-indigo-700 underline disabled:opacity-50" @click="defaultSelection.post(`${baseUrl}/stacks/${stack.id}/default`)">Make default</button><Link :href="`${baseUrl}/stacks/${stack.id}`" class="font-medium text-indigo-700 underline">View stack</Link></td></tr></tbody></table><p v-if="!stacks.data.length" class="px-5 py-10 text-center text-sm text-gray-500">No saved stacks yet. Create one from a discovery recommendation.</p></div><Pagination :links="stacks.links" /></section>
    </div>
</template>
