<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
import { baseUrl } from './engine-ui';

const props = defineProps({ stack: Object, engines: Array, analysis: { type: Object, default: null } });
const name = ref(props.stack.name);
const engineId = ref('');
const action = useForm({});
const saveName = () => action.transform(() => ({ name: name.value })).patch(`${baseUrl}/stacks/${props.stack.id}`);
const addEngine = () => action.transform(() => ({ engine_id: engineId.value })).post(`${baseUrl}/stacks/${props.stack.id}/members`);
const removeMember = member => action.delete(`${baseUrl}/stacks/${props.stack.id}/members/${member.id}`);
const deleteStack = () => action.delete(`${baseUrl}/stacks/${props.stack.id}`);
const makeDefault = () => action.post(`${baseUrl}/stacks/${props.stack.id}/default`);
const reorder = (from, to) => {
    const ids = props.stack.members.map(member => member.id);
    ids.splice(to, 0, ids.splice(from, 1)[0]);
    action.transform(() => ({ member_ids: ids })).put(`${baseUrl}/stacks/${props.stack.id}/members/order`);
};
</script>

<template>
    <Head :title="stack.name" />
    <div class="mx-auto max-w-5xl space-y-6 px-4 py-8 sm:px-6">
        <header class="flex flex-wrap items-end justify-between gap-4 border-b border-gray-200 pb-5"><div><Link :href="`${baseUrl}?tab=stacks`" class="text-sm font-medium text-indigo-700">SAT Engines / Stacks</Link><h1 class="mt-2 text-2xl font-semibold text-gray-950">{{ stack.name }}<span v-if="stack.is_default" class="ml-2 text-base font-normal text-gray-500">(default)</span></h1><p class="mt-1 text-sm text-gray-600">Every Engine participates in the explicit priority order below.</p></div><div class="flex gap-2"><button v-if="!stack.is_default" type="button" :disabled="!stack.members.length || action.processing" class="rounded-lg border border-indigo-200 px-3 py-2 text-sm font-medium text-indigo-700 transition-colors duration-150 hover:bg-indigo-50 disabled:opacity-50 motion-reduce:transition-none" @click="makeDefault">Make default</button><button type="button" :disabled="action.processing" class="rounded-lg border border-red-200 px-3 py-2 text-sm font-medium text-red-700 transition-colors duration-150 hover:bg-red-50 disabled:opacity-50 motion-reduce:transition-none" @click="deleteStack">Delete stack</button></div></header>
        <p v-for="(error, key) in action.errors" :key="key" role="alert" class="text-sm text-red-700">{{ error }}</p>
        <section class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><form class="flex flex-wrap items-end gap-3" @submit.prevent="saveName"><label class="min-w-64 flex-1 text-sm font-medium text-gray-800">Stack name<input v-model="name" required maxlength="160" class="mt-1 w-full rounded-lg border-gray-300" /></label><button :disabled="action.processing" class="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-gray-700 transition-colors duration-150 hover:bg-gray-50 disabled:opacity-50 motion-reduce:transition-none">Save name</button></form></section>
        <section class="overflow-x-auto rounded-xl border border-gray-200 bg-white shadow-sm"><table class="w-full text-left text-sm"><thead class="border-b border-gray-200 bg-gray-50 text-xs font-medium uppercase tracking-wide text-gray-500"><tr><th class="px-4 py-3">Priority</th><th class="px-4 py-3">Engine</th><th class="px-4 py-3 text-right">Test record</th><th class="px-4 py-3 text-right">Win %</th><th class="px-4 py-3 text-right">Coverage</th><th class="px-4 py-3 text-right">Added record</th><th class="px-4 py-3 text-right">Stack impact</th><th class="px-4 py-3"><span class="sr-only">Actions</span></th></tr></thead><tbody><tr v-for="(member, index) in stack.members" :key="member.id" class="border-b border-gray-100 last:border-0"><td class="px-4 py-3 font-medium tabular-nums text-gray-500">{{ index + 1 }}</td><td class="px-4 py-3 font-medium text-gray-900">{{ member.engine.name }}</td><td class="px-4 py-3 text-right tabular-nums">{{ member.engine.discovery_metrics ? `${member.engine.discovery_metrics.wins}–${member.engine.discovery_metrics.losses}` : '—' }}</td><td class="px-4 py-3 text-right tabular-nums">{{ member.engine.discovery_win_pct == null ? '—' : `${Number(member.engine.discovery_win_pct).toFixed(1)}%` }}</td><td class="px-4 py-3 text-right tabular-nums">{{ member.engine.discovery_coverage_pct == null ? '—' : `${Number(member.engine.discovery_coverage_pct).toFixed(1)}%` }}</td><td class="px-4 py-3 text-right tabular-nums">{{ analysis?.candidates[index] ? `${analysis.candidates[index].stack_wins}–${analysis.candidates[index].stack_losses}` : '—' }}</td><td class="px-4 py-3 text-right tabular-nums">{{ analysis?.candidates[index] ? `${Number(analysis.candidates[index].stack_win_pct).toFixed(1)}% / ${Number(analysis.candidates[index].stack_coverage_pct).toFixed(1)}%` : '—' }}</td><td class="px-4 py-3"><div class="flex justify-end gap-2"><button type="button" :disabled="index === 0 || action.processing" class="rounded border border-gray-300 px-2 py-1 text-xs disabled:opacity-40" aria-label="Move earlier" @click="reorder(index, index - 1)">↑</button><button type="button" :disabled="index === stack.members.length - 1 || action.processing" class="rounded border border-gray-300 px-2 py-1 text-xs disabled:opacity-40" aria-label="Move later" @click="reorder(index, index + 1)">↓</button><button type="button" :disabled="action.processing" class="text-sm text-red-700 underline" @click="removeMember(member)">Remove</button></div></td></tr></tbody></table><p v-if="!stack.members.length" class="px-5 py-10 text-center text-sm text-gray-500">This stack has no Engines.</p></section>
        <section class="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><h2 class="text-base font-semibold text-gray-950">Add an existing Engine</h2><form class="mt-4 flex flex-wrap gap-2" @submit.prevent="addEngine"><select v-model="engineId" required class="min-w-64 flex-1 rounded-lg border-gray-300 text-sm"><option disabled value="">Select an Engine</option><option v-for="engine in engines.filter(engine => !stack.members.some(member => member.engine_id === engine.id))" :key="engine.id" :value="engine.id">{{ engine.name }}</option></select><button :disabled="action.processing" class="rounded-lg bg-gray-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">Add Engine</button></form></section>
    </div>
</template>
